version: '3.8'

services:
  php:
    build:
      context: ./php
    container_name: php-container
    volumes:
      - ./src:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9000:9000"

  nginx:
    image: nginx:latest
    container_name: nginx-container
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php/php.ini:/usr/local/etc/php/php.ini
      
    ports:
      - "8080:80"
    depends_on:
      - php
